<?php

switch($CONFIG['SYS_LANG'])
    {
    case 'fr' :
                $LANGUE['accesok'] = 'Acces Autorisé';
                $LANGUE['accesrf'] = 'Acces Refusé';
                $LANGUE['Configuration'] = 'Configuration';
                $LANGUE['MAIN_TITLE'] = '&nbsp;Titre du script';
                $LANGUE['SYS_LANG'] = '&nbsp;Langue';
                $LANGUE['WIDTH_TREE_FRAME'] = '&nbsp;Largeur de la frame de gauche';
                $LANGUE['FRAME_BORDER'] = '&nbsp;Barre entre les deux frames';
                $LANGUE['WIDTH_FRAME_BORDER'] = '&nbsp;Largeur de la bordure entre les frames';
                $LANGUE['WIDTH_FRAME_SPACING'] = "&nbsp;Largeur de l'espacement entre les frames";
                $LANGUE['SCROLING_TREE_FRAME'] = '&nbsp;ScrollBarre entre les deux frames';
                $LANGUE['RESIZE_FRAME'] = '&nbsp;Modifier manuellement la taille des frames';
                $LANGUE['DOCUMENT_ROOT'] = '&nbsp;Document root';
                $LANGUE['WIDTH_TD_SIZE'] = '&nbsp;Largeur de la colone "taille des fichiers"';
                $LANGUE['WIDTH_TD_TYPE'] = '&nbsp;Largeur de la colone "type de fichier"';
                $LANGUE['WIDTH_TD_DATE'] = '&nbsp;Largeur de la colone "date des fichiers"';
                $LANGUE['STYLE'] = '&nbsp;Theme icones';
                $LANGUE['CSS'] = '&nbsp;Theme CSS';
                $LANGUE['TOTALSIZE'] = '&nbsp;Espace Web Disponible';
                $LANGUE['MASK_TYPE_FILES'] = '&nbsp;Extension cach&eacute;e (separ&eacute; par des virgules)';
                $LANGUE['CHECK_MAJ'] = '&nbsp;Pr&eacute;venir des mises &agrave; jour';
                $LANGUE['IMAGE_BROWSER'] = '&nbsp;Gestionnaire de navigation des images';
                $LANGUE['IMAGE_TN'] = '&nbsp;Gestionnaire de selection automatique vignettes/liste';
                $LANGUE['GD2'] = "&nbsp;Support GD2 (d&eacute;sactivez en cas d'erreur avec les vignettes)";
                $LANGUE['IMAGE_JPG'] = '&nbsp;Support JPG/PNG pour la cr&eacute;ation des vignettes';
                $LANGUE['IMAGE_GIF'] = '&nbsp;Support GIF pour la cr&eacute;ation des vignettes';
                $LANGUE['IMAGE_BMP'] = '&nbsp;Support BMP pour la cr&eacute;ation des vignettes';
                $LANGUE['IMAGE_TN_SIZE'] = '&nbsp;Taille des vignettes';
                $LANGUE['IMAGE_TN_COMPRESSION'] = '&nbsp;Taux de compression des vignettes';
                $LANGUE['NB_COLL_TN'] = '&nbsp;Nombre de vignettes par ligne';
                $LANGUE['EXIF_READER'] = '&nbsp;Support EXIF';
                $LANGUE['SLIDE_SHOW'] = '&nbsp;Diaporama';
                $LANGUE['DEBUG'] = '&nbsp;Debug (pour devellopement)';
                $LANGUE['oui'] = 'Oui';
                $LANGUE['non'] = 'Non';
                $LANGUE['auto'] = 'Auto';
                $LANGUE['MAJ'] = 'Mettre à jour';
                $LANGUE['SLIDE_SHOW_INT'] = '&nbsp;Interval entre deux photos';
                $LANGUE['ERR1'] = 'Impossible de sauvegarder fichier de configuration! ';
                $LANGUE['ERR3'] = 'la configuration n\'a pas &eacute;t&eacute; modifi&eacute;! ';
                $LANGUE['ERR2'] = 'Configuration sauvegard&eacute; : config.inc.php.bak';
                $LANGUE['ERR4'] = 'erreur d\'ecriture, restauration de la configuration initial! ';
                $LANGUE['ERR5'] = 'Configuration correctement modifi&eacute;.';
                $LANGUE['BACK'] = '&nbsp;Affiche la fleche de retour';
                $LANGUE['AUTO_RESIZE'] = '&nbsp;Adapte l\'image à la taille de la fenetre';
                $LANGUE['WRITE_TN'] = '&nbsp;Mettre les vignettes en cache';
                $LANGUE['MENU_HIDE'] = 'Cacher un dossier/fichier';
                $LANGUE['STATE'] = 'Status';
                $LANGUE['PATH'] = 'Chemin';
                break;

        case 'eng' :
                $LANGUE['accesok'] = 'Access authorized';
                $LANGUE['accesrf'] = 'Access refused';
                $LANGUE['Configuration'] = 'Configuration';
                $LANGUE['MAIN_TITLE'] = '&nbsp;Title of the script';
                $LANGUE['SYS_LANG'] = '&nbsp;Language';
                $LANGUE['WIDTH_TREE_FRAME'] = '&nbsp;Width of the left frame';
                $LANGUE['FRAME_BORDER'] = '&nbsp;Bar between frames';
                $LANGUE['WIDTH_FRAME_BORDER'] = '&nbsp;Width of the bar';
                $LANGUE['WIDTH_FRAME_SPACING'] = "&nbsp;Width of spacing between the frames";
                $LANGUE['SCROLING_TREE_FRAME'] = '&nbsp;ScrollBar between frames';
                $LANGUE['RESIZE_FRAME'] = '&nbsp;Resize manually width of frames';
                $LANGUE['DOCUMENT_ROOT'] = '&nbsp;Root document';
                $LANGUE['WIDTH_TD_SIZE'] = '&nbsp;Width of the colone "size of the files"';
                $LANGUE['WIDTH_TD_TYPE'] = '&nbsp;Width of the colone "type of the files"';
                $LANGUE['WIDTH_TD_DATE'] = '&nbsp;Width of the colone "date of the files"';
                $LANGUE['STYLE'] = '&nbsp;Icon theme';
                $LANGUE['CSS'] = '&nbsp;CSS theme';
                $LANGUE['TOTALSIZE'] = '&nbsp;Free Web space';
                $LANGUE['MASK_TYPE_FILES'] = '&nbsp;Hidden extension (separated by commas)';
                $LANGUE['CHECK_MAJ'] = '&nbsp;Check update';
                $LANGUE['IMAGE_BROWSER'] = '&nbsp;Manager of navigation of the pictures';
                $LANGUE['IMAGE_TN'] = '&nbsp;Manager of automatic selection Thumbnail/list';
                $LANGUE['GD2'] = "&nbsp;GD2 support (disable if thumbnail error)";
                $LANGUE['IMAGE_JPG'] = '&nbsp;JPG/PNG support for thumbnail';
                $LANGUE['IMAGE_GIF'] = '&nbsp;GIF support for thumbnail';
                $LANGUE['IMAGE_BMP'] = '&nbsp;BMP support for thumbnail';
                $LANGUE['IMAGE_TN_SIZE'] = '&nbsp;Width oh thumbnail';
                $LANGUE['IMAGE_TN_COMPRESSION'] = '&nbsp;Compression ratio of the thumbnails';
                $LANGUE['NB_COLL_TN'] = '&nbsp;Number of thumbnails per line';
                $LANGUE['EXIF_READER'] = '&nbsp;EXIF support';
                $LANGUE['SLIDE_SHOW'] = '&nbsp;Slideshow';
                $LANGUE['DEBUG'] = '&nbsp;Debug (only for development)';
                $LANGUE['oui'] = 'Yes';
                $LANGUE['non'] = 'No';
                $LANGUE['auto'] = 'Auto';
                $LANGUE['MAJ'] = 'Update';
                $LANGUE['SLIDE_SHOW_INT'] = '&nbsp;Time between two fotos';
                $LANGUE['ERR1'] = 'Impossible to safeguard file of configuration! ';
                $LANGUE['ERR3'] = 'the configuration was not modified';
                $LANGUE['ERR2'] = 'Configuration saved:  config.inc.php.bak';
                $LANGUE['ERR4'] = 'write error, restoration of the configuration initial!';
                $LANGUE['ERR5'] = 'Configuration correctly modified.';
                $LANGUE['BACK'] = '&nbsp;Show Back link';
                $LANGUE['AUTO_RESIZE'] = '&nbsp;Adapt the image to the size of the window';
                $LANGUE['WRITE_TN'] = '&nbsp;Put thumbnail in memory';
                $LANGUE['MENU_HIDE'] = 'Hide a directory/file';
                $LANGUE['STATE'] = 'State';
                $LANGUE['PATH'] = 'Path';
                break;

        case 'de' : //-- A faire car je parle pas allemand et voila.fr est pas très doué :o/
                $LANGUE['accesok'] = 'erlaubter Zugang';
                $LANGUE['accesrf'] = 'abgelehnter Zugang';
                $LANGUE['Configuration'] = 'Konfiguration';
                $LANGUE['MAIN_TITLE'] = 'Titre du script';
                $LANGUE['SYS_LANG'] = 'Sprache';
                $LANGUE['WIDTH_TREE_FRAME'] = 'Largeur de la frame de gauche';
                $LANGUE['FRAME_BORDER'] = 'Barre entre les deux frames';
                $LANGUE['WIDTH_FRAME_BORDER'] = 'Largeur de la bordure entre les frames';
                $LANGUE['WIDTH_FRAME_SPACING'] = "Largeur de l'espacement entre les frames";
                $LANGUE['SCROLING_TREE_FRAME'] = 'ScrollBar entre les deux frames';
                $LANGUE['RESIZE_FRAME'] = 'Modifier manuellement la taille des frames';
                $LANGUE['DOCUMENT_ROOT'] = 'Document root';
                $LANGUE['WIDTH_TD_SIZE'] = 'Largeur de la colone "taille des fichiers"';
                $LANGUE['WIDTH_TD_TYPE'] = 'Largeur de la colone "type de fichier"';
                $LANGUE['WIDTH_TD_DATE'] = 'Largeur de la colone "date des fichiers"';
                $LANGUE['STYLE'] = 'Theme icones';
                $LANGUE['CSS'] = 'Theme CSS';
                $LANGUE['TOTALSIZE'] = 'Espace Web Disponible';
                $LANGUE['MASK_TYPE_FILES'] = 'Extension cach&eacute;e (separ&eacute; par des virgules)';
                $LANGUE['CHECK_MAJ'] = 'Pr&eacute;venir des mises &agrave; jour';
                $LANGUE['IMAGE_BROWSER'] = 'Gestionnaire de navigation des images';
                $LANGUE['IMAGE_TN'] = 'Gestionnaire de selection automatique vignettes/liste';
                $LANGUE['GD2'] = "Support GD2 (d&eacute;sactivez en cas d'erreur avec les vignettes)";
                $LANGUE['IMAGE_JPG'] = 'Support JPG/PNG pour la cr&eacute;ation des vignettes';
                $LANGUE['IMAGE_GIF'] = 'Support GIF pour la cr&eacute;ation des vignettes';
                $LANGUE['IMAGE_BMP'] = 'Support BMP pour la cr&eacute;ation des vignettes';
                $LANGUE['IMAGE_TN_SIZE'] = 'Taille des vignettes';
                $LANGUE['IMAGE_TN_COMPRESSION'] = 'Taux de compression des vignettes';
                $LANGUE['NB_COLL_TN'] = 'Nombre de vignettes par ligne';
                $LANGUE['EXIF_READER'] = 'Support EXIF';
                $LANGUE['SLIDE_SHOW'] = 'Diaporama';
                $LANGUE['DEBUG'] = 'Debug (pour devellopement)';
                $LANGUE['oui'] = 'Ja';
                $LANGUE['non'] = 'Nicht';
                $LANGUE['auto'] = 'Auto';
                $LANGUE['MAJ'] = 'Update';
                $LANGUE['SLIDE_SHOW_INT'] = 'Interval entre deux photos';
                $LANGUE['ERR1'] = 'Impossible de sauvegarder fichier de configuration! ';
                $LANGUE['ERR3'] = 'la configuration n\'a pas &eacute;t&eacute; modifi&eacute;! ';
                $LANGUE['ERR2'] = 'Configuration sauvegard&eacute; : config.inc.php.bak';
                $LANGUE['ERR4'] = 'erreur d\'ecriture, restauration de la configuration initial! ';
                $LANGUE['ERR5'] = 'Configuration correctement modifi&eacute;.';
                $LANGUE['BACK'] = 'Affiche la fleche de retour';
                $LANGUE['AUTO_RESIZE'] = '&nbsp;Adapte l\'image a la taille de la fenetre';
                $LANGUE['WRITE_TN'] = '&nbsp;Put thumbnail in memory';
                $LANGUE['MENU_HIDE'] = 'Cacher un dossier/fichier';
                $LANGUE['STATE'] = 'State';
                $LANGUE['PATH'] = 'Path';
                break;

        default :
                die('<font size="1" face="MS Sans Serif, Courier, Arial" color="red" ><b>-ERREUR-</b><br />Probleme de selection de la langue dans le fichier \'config.inc.php\'</font>');
        }

?>
